# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zss_train.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='zss_train.proto',
  package='ZSS.Protocol',
  serialized_pb=_b('\n\x0fzss_train.proto\x12\x0cZSS.Protocol\"x\n\x0cTrainControl\x12/\n\x05state\x18\x01 \x01(\x0e\x32 .ZSS.Protocol.TrainControl.State\"7\n\x05State\x12\t\n\x05READY\x10\x00\x12\x07\n\x03RUN\x10\x01\x12\x0f\n\x0b\x43\x41LC_REWARD\x10\x02\x12\t\n\x05RESET\x10\x03\"8\n\nMessiInput\x12\r\n\x05\x65nemy\x18\x01 \x01(\x05\x12\x0c\n\x04\x64ist\x18\x02 \x01(\x02\x12\r\n\x05\x61ngel\x18\x03 \x01(\x02\":\n\x0bMessiOutput\x12\r\n\x05vel_x\x18\x01 \x01(\x02\x12\r\n\x05vel_y\x18\x02 \x01(\x02\x12\r\n\x05vel_w\x18\x03 \x01(\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_TRAINCONTROL_STATE = _descriptor.EnumDescriptor(
  name='State',
  full_name='ZSS.Protocol.TrainControl.State',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='READY', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RUN', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CALC_REWARD', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESET', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=98,
  serialized_end=153,
)
_sym_db.RegisterEnumDescriptor(_TRAINCONTROL_STATE)


_TRAINCONTROL = _descriptor.Descriptor(
  name='TrainControl',
  full_name='ZSS.Protocol.TrainControl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='ZSS.Protocol.TrainControl.state', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TRAINCONTROL_STATE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=153,
)


_MESSIINPUT = _descriptor.Descriptor(
  name='MessiInput',
  full_name='ZSS.Protocol.MessiInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='enemy', full_name='ZSS.Protocol.MessiInput.enemy', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dist', full_name='ZSS.Protocol.MessiInput.dist', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='angel', full_name='ZSS.Protocol.MessiInput.angel', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=211,
)


_MESSIOUTPUT = _descriptor.Descriptor(
  name='MessiOutput',
  full_name='ZSS.Protocol.MessiOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vel_x', full_name='ZSS.Protocol.MessiOutput.vel_x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vel_y', full_name='ZSS.Protocol.MessiOutput.vel_y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vel_w', full_name='ZSS.Protocol.MessiOutput.vel_w', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=271,
)

_TRAINCONTROL.fields_by_name['state'].enum_type = _TRAINCONTROL_STATE
_TRAINCONTROL_STATE.containing_type = _TRAINCONTROL
DESCRIPTOR.message_types_by_name['TrainControl'] = _TRAINCONTROL
DESCRIPTOR.message_types_by_name['MessiInput'] = _MESSIINPUT
DESCRIPTOR.message_types_by_name['MessiOutput'] = _MESSIOUTPUT

TrainControl = _reflection.GeneratedProtocolMessageType('TrainControl', (_message.Message,), dict(
  DESCRIPTOR = _TRAINCONTROL,
  __module__ = 'zss_train_pb2'
  # @@protoc_insertion_point(class_scope:ZSS.Protocol.TrainControl)
  ))
_sym_db.RegisterMessage(TrainControl)

MessiInput = _reflection.GeneratedProtocolMessageType('MessiInput', (_message.Message,), dict(
  DESCRIPTOR = _MESSIINPUT,
  __module__ = 'zss_train_pb2'
  # @@protoc_insertion_point(class_scope:ZSS.Protocol.MessiInput)
  ))
_sym_db.RegisterMessage(MessiInput)

MessiOutput = _reflection.GeneratedProtocolMessageType('MessiOutput', (_message.Message,), dict(
  DESCRIPTOR = _MESSIOUTPUT,
  __module__ = 'zss_train_pb2'
  # @@protoc_insertion_point(class_scope:ZSS.Protocol.MessiOutput)
  ))
_sym_db.RegisterMessage(MessiOutput)


# @@protoc_insertion_point(module_scope)
